### ISSUE TITLE
repeat={true}일 때의 대상 요소 투명화 현상

### ISSUE THREAD

**Issue by sosyjin** [LasBe-code/react-scroll-animation#1]
문제: ScrollAnimation 태그의 repeat 옵션이 true이고, 대상 요소의 display가 flex일 때, 대상 요소가 투명화(opacity:0) 되는 현상이 불편하게 느껴집니다.

원인 및 해결: display:flex이면, 대상 요소가 ScrollAnimation에 의해 좌/우에서 Viewport로 미끄러져 오기 전, 즉 화면 밖에서 이미 /src/lib.react-scroll-animation/useScrollAnimation.ts의 line:24 : if(repeat) setIsInViewport(false); 가 실행되면서 isInViewport가 false로 설정... 그리고 opacity가 0이 되기 때문에 위와 같은 현상이 발생한 것으로 예상합니다.

요약: 요약하자면 이는 꼭 repeat 옵션이 true, 대상 요소의 display가 flex와 같이 너비/높이가 정해진 요소일 때 발생하는 현상이라는 것입니다.

그 외: 이것이 해결해야 하는 현상인지, 필요에 의한 현상인지는 모르겠으나 기능을 사용함에 있어 문제에 직면했고, 이를 필요에 의해 해결했으므로 제 고찰과 함께 Issue를 남깁니다.
 유용한 기능 개발해주셔서 감사합니다!

**Comment by sosyjin** [comment]
참고로 'Ctrl+스크롤'을 통해 화면을 축소하면 요소가 보입니다. 이는 위 글의 원인 및 해결에서 '화면 밖에서...'에서 의미하는 화면 밖에 해당하는 위치를 화면이 축소되면서 포함하게 되기 때문이 아닐까 싶습니다.

**Comment by devlasbe** [comment]
안녕하세요.
우선 이슈를 남겨주셔서 정말 감사하고, 뒤늦게 코멘트를 남겨 죄송합니다.

코드가 첨부되었으면 좋겠지만 아마 말씀하신 현상은 요소가 아예 화면 밖으로 나가 트리거 되지 않는 현상인 것으로 예상됩니다.
그것까지 사용자가 계산해서 사용하도록 의도하여 개발하였기 때문에 추가적인 수정은 없을 것 같습니다.

마지막으로 사용해주셔서 감사합니다 😊
